[package]
name = "hcscrgen"
description = "Home computer screendump generator"
authors = ["Stefan Schramm <mail@stefanschramm.net>"]
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
rand = "0.8.5"
