[package]
name = "hcscrgen"
description = "Home computer screen contents generator"
authors = ["Stefan Schramm <mail@stefanschramm.net>"]
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
image = "0.25.5"
rand = "0.8.5"
